import { Bar, BarZone } from './types';

export const BARS_B: Bar[] = [
  {
    "id": "tough-love-cask",
    "name": "Tough Love Tap Room (Cask) (Porto)",
    "zone": BarZone.PORTO,
    "address": "R. Guilherme Gomes Fernandes 5, 3800-197",
    "workingHours": "Consultar horários no site oficial / redes sociais.",
    "workingHoursPT": "Consultar horários no site oficial / redes sociais.",
    "workingHoursEN": "Check working hours on the official website / social media.",
    "styles": [
      "Cask Ale",
      "Bitter",
      "Stout",
      "Pilsner"
    ],
    "description": "Tap room da aclamada cervejeira de Aveiro conhecida pelas suas cervejas audazes.",
    "descriptionPT": "Tap room da aclamada cervejeira de Aveiro conhecida pelas suas cervejas audazes.",
    "descriptionEN": "Taproom of the acclaimed Aveiro brewery known for its bold beers.",
    "rating": 4.8,
    "reviewsCount": 154,
    "coverPhoto": "https://images.squarespace-cdn.com/content/v1/61e94a43b03e8e6c92a7ab39/54e28eff-2c03-4352-8761-791e9b25773f/03C.jpg?format=500w",
    "instagramUrl": "https://www.instagram.com/toughloveaveiro/",
    "facebookUrl": "https://www.facebook.com/Toughlovetaproomaveiro/?locale=pt_PT",
    "latitude": 40.64325662301811,
    "longitude": -8.650511510630684,
    "hasApplePay": true
  },
  {
    "id": "gulden-draak-porto",
    "name": "Gulden Draak Bierhuis (Porto)",
    "zone": BarZone.PORTO,
    "address": "R. de José Falcão N. 82, 4050-315",
    "workingHours": "Domingo a Quinta 17:00h às 00:00h\nSexta, Sábado e Vésperas de Feriado 17:00h às 02:00h",
    "workingHoursPT": "Domingo a Quinta 17:00h às 00:00h\nSexta, Sábado e Vésperas de Feriado 17:00h às 02:00h",
    "workingHoursEN": "Sunday to Thursday 17:00 to 00:00\nFriday, Saturday and Holiday Eves 17:00 to 02:00",
    "styles": [
      "Belgian Tripel",
      "Quadrupel",
      "Dubbel",
      "Blond Ale"
    ],
    "description": "A embaixada da famosa cerveja belga no Porto com 16 torneiras de pressão e mais de 350 rótulos em garrafa.",
    "descriptionPT": "A embaixada da famosa cerveja belga no Porto com 16 torneiras de pressão e mais de 350 rótulos em garrafa.",
    "descriptionEN": "The embassy of the famous Belgian beer in Porto with 16 draft taps and over 350 bottled labels.",
    "rating": 4.9,
    "reviewsCount": 425,
    "coverPhoto": "https://images.squarespace-cdn.com/content/v1/61e94a43b03e8e6c92a7ab39/5e2a0ac4-eac9-4622-9e4f-bfb0b500b741/12P.jpg?format=500w",
    "instagramUrl": "https://www.instagram.com/guldendraak.porto/",
    "facebookUrl": "https://www.facebook.com/guldendraakbierhuisporto/",
    "latitude": 41.14858050729378,
    "longitude": -8.614261058564534,
    "hasApplePay": true
  },
  {
    "id": "baobab-porto",
    "name": "Baobab Craft Beer Bar (Porto)",
    "zone": BarZone.PORTO,
    "address": "Rua do Almada 377, 4000-303",
    "workingHours": "Ter a Dom: 17:00h às 01:00h",
    "workingHoursPT": "Ter a Dom: 17:00h às 01:00h",
    "workingHoursEN": "Tue to Sun: 17:00 to 01:00",
    "styles": [
      "NEIPA",
      "Double IPA",
      "Sour",
      "Imperial Stout"
    ],
    "description": "Bar acolhedor em Cedofeita com foco em microcervejeiras independentes.",
    "descriptionPT": "Bar acolhedor em Cedofeita com foco em microcervejeiras independentes.",
    "descriptionEN": "Cozy bar in Cedofeita focusing on independent microbreweries.",
    "rating": 4.7,
    "reviewsCount": 94,
    "coverPhoto": "https://images.squarespace-cdn.com/content/v1/61e94a43b03e8e6c92a7ab39/e57e078d-050f-46e7-8d77-ba68bf58fe0f/01P.jpg?format=500w",
    "instagramUrl": "https://www.instagram.com/baobab_craftbeer/",
    "facebookUrl": "https://www.facebook.com/p/Baobab-craftbeer-Porto-100083390616590/",
    "latitude": 41.15039178961273,
    "longitude": -8.612129845346207,
    "hasApplePay": true
  },
  {
    "id": "cervejaria-carmo",
    "name": "Cervejaria do Carmo (Porto)",
    "zone": BarZone.PORTO,
    "address": "Praça de Carlos Alberto 124, 4050-159",
    "workingHours": "Consultar horários no local.",
    "workingHoursPT": "Consultar horários no local.",
    "workingHoursEN": "Check working hours on site.",
    "styles": [
      "Lager",
      "Pilsner",
      "Amber Ale",
      "Stout"
    ],
    "description": "Ponto de encontro clássico com seleção de cervejas (incluindo artesanais) e petiscos tradicionais.",
    "descriptionPT": "Ponto de encontro clássico com seleção de cervejas (incluindo artesanais) e petiscos tradicionais.",
    "descriptionEN": "Classic meeting spot with a selection of beers (including craft) and traditional snacks.",
    "rating": 4.5,
    "reviewsCount": 188,
    "coverPhoto": "https://images.squarespace-cdn.com/content/v1/61e94a43b03e8e6c92a7ab39/8a10f765-6f73-4eb7-9618-b9fa5ea8ab6d/02P.jpg?format=500w",
    "instagramUrl": "https://www.instagram.com/cervejariadocarmo/",
    "facebookUrl": "https://www.facebook.com/cervejariadocarmo/%3Flocale%3Dpt_PT",
    "latitude": 41.1476058248274,
    "longitude": -8.61592538872468,
    "hasApplePay": true
  },
  {
    "id": "musa-virtudes",
    "name": "MUSA das Virtudes (Porto)",
    "zone": BarZone.PORTO,
    "address": "Passeio das Virtudes 28, 4050-629",
    "workingHours": "Seg a Dom: 16:00h às 00:00h",
    "workingHoursPT": "Seg a Dom: 16:00h às 00:00h",
    "workingHoursEN": "Mon to Sun: 16:00 to 00:00",
    "styles": [
      "Pilsner",
      "Session IPA",
      "Sour",
      "Stout"
    ],
    "description": "Espaço da Musa no Porto com vista deslumbrante sobre o Rio Douro e comida excelente.",
    "descriptionPT": "Espaço da Musa no Porto com vista deslumbrante sobre o Rio Douro e comida excelente.",
    "descriptionEN": "Musa spot in Porto with a stunning view over the Douro River and great food.",
    "rating": 4.8,
    "reviewsCount": 312,
    "coverPhoto": "https://images.squarespace-cdn.com/content/v1/61e94a43b03e8e6c92a7ab39/8ff5aa76-fd52-486a-a27c-360ecaed66de/03P.jpg?format=500w",
    "instagramUrl": "https://www.instagram.com/musadasvirtudes/",
    "facebookUrl": "https://www.facebook.com/musadasvirtudes/%3Flocale%3Dpt_BR",
    "latitude": 41.143976745673676,
    "longitude": -8.61815821947602,
    "hasApplePay": true
  },
  {
    "id": "catraio",
    "name": "Catraio Craft Beer Shop & Bar (Porto)",
    "zone": BarZone.PORTO,
    "address": "R. de Cedofeita 256, 4050-174",
    "workingHours": "Seg a Qui: 16:00h às 00:00h\nSex e Sáb: 16:00h às 02:00h",
    "workingHoursPT": "Seg a Qui: 16:00h às 00:00h\nSex e Sáb: 16:00h às 02:00h",
    "workingHoursEN": "Mon to Thu: 16:00 to 00:00\nFri and Sat: 16:00 to 02:00",
    "styles": [
      "NEIPA",
      "Sour",
      "Stout",
      "West Coast IPA"
    ],
    "description": "O primeiro bar de cerveja artesanal no Porto. Ambiente místico com jardim interior e seleção variada.",
    "descriptionPT": "O primeiro bar de cerveja artesanal no Porto. Ambiente místico com jardim interior e seleção variada.",
    "descriptionEN": "The first craft beer bar in Porto. Mystical atmosphere with an inner garden and a varied selection.",
    "rating": 4.8,
    "reviewsCount": 342,
    "coverPhoto": "https://images.squarespace-cdn.com/content/v1/61e94a43b03e8e6c92a7ab39/fbab0b98-509b-4713-9581-2e4dc4c6fa59/04P.jpg?format=500w",
    "instagramUrl": "https://www.instagram.com/catraiocraftbeer/",
    "facebookUrl": "https://www.facebook.com/CatraioCraftBeer",
    "latitude": 41.1511201428873,
    "longitude": -8.617286141986535,
    "hasApplePay": true
  },
  {
    "id": "nortada",
    "name": "Nortada Taproom (Porto)",
    "zone": BarZone.PORTO,
    "address": "R. de Sá da Bandeira 210, 4000-427",
    "workingHours": "Dom a Qui: 12:00h às 00:00h\nSex e Sáb: 12:00h às 02:00h",
    "workingHoursPT": "Dom a Qui: 12:00h às 00:00h\nSex e Sáb: 12:00h às 02:00h",
    "workingHoursEN": "Sun to Thu: 12:00 to 00:00\nFri and Sat: 12:00 to 02:00",
    "styles": [
      "Lager",
      "IPA",
      "Weissbier",
      "Stout"
    ],
    "description": "A casa da Cerveja Nortada no centro do Porto, com fábrica visível e menu completo.",
    "descriptionPT": "A casa da Cerveja Nortada no centro do Porto, com fábrica visível e menu completo.",
    "descriptionEN": "The home of Cerveja Nortada in downtown Porto, featuring a visible brewery and full menu.",
    "rating": 4.6,
    "reviewsCount": 512,
    "coverPhoto": "https://images.squarespace-cdn.com/content/v1/61e94a43b03e8e6c92a7ab39/67b57a1e-d76e-4464-ac6f-118b334d66eb/06P.jpg?format=500w",
    "instagramUrl": "https://www.instagram.com/cervejanortada/",
    "facebookUrl": "https://www.facebook.com/cervejarianortada.porto",
    "latitude": 41.14796797908326,
    "longitude": -8.60817987325347,
    "hasApplePay": true
  },
  {
    "id": "armazem-da-cerveja",
    "name": "Armazém da Cerveja (Porto)",
    "zone": BarZone.PORTO,
    "address": "R. Formosa 130, 4000-254",
    "workingHours": "Ter a Sáb: 16:00h às 00:00h",
    "workingHoursPT": "Ter a Sáb: 16:00h às 00:00h",
    "workingHoursEN": "Tue to Sat: 16:00 to 00:00",
    "styles": [
      "IPA",
      "Barleywine",
      "Sour",
      "Weizenbock"
    ],
    "description": "Loja e bar com excelente curadoria de cervejas nacionais e importadas.",
    "descriptionPT": "Loja e bar com excelente curadoria de cervejas nacionais e importadas.",
    "descriptionEN": "Shop and bar with an excellent curated selection of national and imported beers.",
    "rating": 4.7,
    "reviewsCount": 168,
    "coverPhoto": "https://images.squarespace-cdn.com/content/v1/61e94a43b03e8e6c92a7ab39/17feb2da-8134-4bb4-9b1c-d72025079fa3/07P.jpg?format=500w",
    "instagramUrl": "https://www.instagram.com/explore/locations/436104783445908/armazem-da-cerveja-craft-beer-bar-shop/",
    "facebookUrl": "https://www.facebook.com/ArmazemCerveja/",
    "latitude": 41.14764684654752,
    "longitude": -8.603760596793526,
    "hasApplePay": true
  },
  {
    "id": "fabrica-da-picaria",
    "name": "A Fábrica da Picaria (Porto)",
    "zone": BarZone.PORTO,
    "address": "Rua da Picaria 72, 4050-477",
    "workingHours": "Ter a Dom: 12:00h às 00:00h",
    "workingHoursPT": "Ter a Dom: 12:00h às 00:00h",
    "workingHoursEN": "Tue to Sun: 12:00 to 00:00",
    "styles": [
      "Pilsner",
      "IPA",
      "Stout",
      "Red Ale"
    ],
    "description": "Cervejaria onde a cerveja é produzida à vista dos clientes no centro histórico.",
    "descriptionPT": "Cervejaria onde a cerveja é produzida à vista dos clientes no centro histórico.",
    "descriptionEN": "Brewpub where beer is brewed right in front of customers in the historic center.",
    "rating": 4.7,
    "reviewsCount": 298,
    "coverPhoto": "https://images.squarespace-cdn.com/content/v1/61e94a43b03e8e6c92a7ab39/9097c235-5003-4f9e-9c96-22ee348fd452/08P.jpg?format=500w",
    "instagramUrl": "https://www.instagram.com/afabricadapicaria/",
    "facebookUrl": "https://www.facebook.com/afabricadapicaria/%3Flocale%3Dpt_PT",
    "latitude": 41.14956020504939,
    "longitude": -8.61286721472359,
    "hasApplePay": true
  },
  {
    "id": "levare-brewpub",
    "name": "Cervejaria Levare (Porto)",
    "zone": BarZone.PORTO,
    "address": "Praça da Batalha 12A, 4049-055",
    "workingHours": "Diariamente: 12:00h às 23:00h",
    "workingHoursPT": "Diariamente: 12:00h às 23:00h",
    "workingHoursEN": "Daily: 12:00 to 23:00",
    "styles": [
      "Lager",
      "Blond Ale",
      "Dunkel",
      "IPA"
    ],
    "description": "Restauração e produção própria de cerveja artesanal em pleno Porto.",
    "descriptionPT": "Restauração e produção própria de cerveja artesanal em pleno Porto.",
    "descriptionEN": "Restaurant with in-house craft beer brewing in the heart of Porto.",
    "rating": 4.5,
    "reviewsCount": 147,
    "coverPhoto": "https://images.squarespace-cdn.com/content/v1/61e94a43b03e8e6c92a7ab39/89052570-f4a0-4df6-9657-75a297a0d660/09P.jpg?format=500w",
    "instagramUrl": "https://www.instagram.com/levare_craftbeer/",
    "facebookUrl": "https://www.facebook.com/levarecraftbeer/%3Flocale%3Dpt_PT",
    "latitude": 41.145851770467914,
    "longitude": -8.606263746279563,
    "hasApplePay": true
  },
  {
    "id": "letraria-downtown",
    "name": "Letraria Porto (Porto)",
    "zone": BarZone.PORTO,
    "address": "Rua dos Mártires da Liberdade 108, 4000-483",
    "workingHours": "Ter a Qui: 17:00h às 00:00h\nSex e Sáb: 17:00h às 01:00h\nDom: 17:00h às 00:00h",
    "workingHoursPT": "Ter a Qui: 17:00h às 00:00h\nSex e Sáb: 17:00h às 01:00h\nDom: 17:00h às 00:00h",
    "workingHoursEN": "Tue to Thu: 17:00 to 00:00\nFri and Sat: 17:00 to 01:00\nSun: 17:00 to 00:00",
    "styles": [
      "Letra A",
      "Letra B",
      "Letra C",
      "Letra D",
      "Letra F"
    ],
    "description": "Espaço amplo com grande jardim no centro do Porto. Dezenas de torneiras da Cerveja Letra.",
    "descriptionPT": "Espaço amplo com grande jardim no centro do Porto. Dezenas de torneiras da Cerveja Letra.",
    "descriptionEN": "Spacious venue with a large garden in central Porto. Dozens of Cerveja Letra taps.",
    "rating": 4.8,
    "reviewsCount": 312,
    "coverPhoto": "https://images.squarespace-cdn.com/content/v1/61e94a43b03e8e6c92a7ab39/d6de3ea9-6f49-4cf2-96b9-eb6a1fb02b21/14P.jpg?format=500w",
    "instagramUrl": "https://www.instagram.com/letrariaporto/",
    "facebookUrl": "https://www.facebook.com/LetrariaPortoDowntown/",
    "latitude": 41.15093903202883,
    "longitude": -8.614035075213907,
    "hasApplePay": true
  },
  {
    "id": "deuses-do-malte",
    "name": "Deuses do Malte (V.N. Gaia)",
    "zone": BarZone.VN_GAIA,
    "address": "Rua soares dos reis 1324 A9 4430-240 VNGaia",
    "workingHours": "Todas as sextas das 18h às 00h",
    "workingHoursPT": "Todas as sextas das 18h às 00h",
    "workingHoursEN": "Every Friday from 18:00 to 00:00",
    "styles": [
      "Lager",
      "NEIPA",
      "Sour",
      "Stout"
    ],
    "description": "Um ambiente rustico e intimista ideal para convívio entre apreciadores. No tap room estão 8 torneiras que são rotativas.",
    "descriptionPT": "Um ambiente rustico e intimista ideal para convívio entre apreciadores. No tap room estão 8 torneiras que são rotativas.",
    "descriptionEN": "A rustic and intimate atmosphere ideal for craft beer lovers. The taproom features 8 rotating taps.",
    "rating": 4.7,
    "reviewsCount": 84,
    "coverPhoto": "https://images.squarespace-cdn.com/content/v1/61e94a43b03e8e6c92a7ab39/ef4cbb37-8eef-4871-9a6d-e2a367d2b2d2/10P.jpg?format=500w",
    "instagramUrl": "https://www.instagram.com/deusesdomalte/",
    "facebookUrl": "https://pt-pt.facebook.com/deusesdomalte",
    "latitude": 41.11192838226133,
    "longitude": -8.605115584522384,
    "hasApplePay": true
  },
  {
    "id": "cerveja-dos-diabos",
    "name": "Cerveja dos Diabos (Porto)",
    "zone": BarZone.PORTO,
    "address": "R. de Pinto Bessa 122 Armazém 2, 4300-427",
    "workingHours": "Consultar horários no local.",
    "workingHoursPT": "Consultar horários no local.",
    "workingHoursEN": "Check working hours on site.",
    "styles": [
      "Red Ale",
      "Belgian Stout",
      "IPA"
    ],
    "description": "Brewery e bar de cerveja local no Porto.",
    "descriptionPT": "Brewery e bar de cerveja local no Porto.",
    "descriptionEN": "Brewery and local beer bar in Porto.",
    "rating": 4.6,
    "reviewsCount": 42,
    "coverPhoto": "https://images.squarespace-cdn.com/content/v1/61e94a43b03e8e6c92a7ab39/fda60f93-ac23-46d7-ba75-295ea74944c5/13P.jpg?format=500w",
    "instagramUrl": "https://www.instagram.com/cerveja_dos_diabos_/",
    "facebookUrl": "https://www.facebook.com/CervejaDosDiabos/%3Flocale%3Dpt_PT",
    "latitude": 41.149665715606446,
    "longitude": -8.587694784020254,
    "hasApplePay": true
  },
  {
    "id": "o-bandido",
    "name": "O Bandido (Porto)",
    "zone": BarZone.PORTO,
    "address": "R. Mte. Guilherme Camarinha, 4200-162",
    "workingHours": "Segunda a Quinta 16:00-1:00\nSexta a Domingo 12:00-1:00",
    "workingHoursPT": "Segunda a Quinta 16:00-1:00\nSexta a Domingo 12:00-1:00",
    "workingHoursEN": "Monday to Thursday 16:00-1:00\nFriday to Sunday 12:00-1:00",
    "styles": [
      "Hazy IPA",
      "Pilsner",
      "Imperial Stout",
      "Fruit Sour"
    ],
    "description": "Culpados de servir os melhores hambúrgueres do Porto e + de 40 cervejas diferentes.",
    "descriptionPT": "Culpados de servir os melhores hambúrgueres do Porto e + de 40 cervejas diferentes.",
    "descriptionEN": "Guilty of serving the best burgers in Porto + over 40 different beers.",
    "rating": 4.7,
    "reviewsCount": 110,
    "coverPhoto": "https://images.squarespace-cdn.com/content/v1/61e94a43b03e8e6c92a7ab39/e6299268-b849-4ca6-8737-9cbf5dc9b868/15P.jpg?format=500w",
    "instagramUrl": "https://www.instagram.com/obandido.pt/",
    "facebookUrl": "https://web.facebook.com/profile.php?id=61557502203540&ref=PROFILE_EDIT_xav_ig_profile_page_web",
    "latitude": 41.18424888489989,
    "longitude": -8.603170134555201,
    "hasApplePay": true
  },
  {
    "id": "canto-do-lobo",
    "name": "Canto do Lobo (Caminha)",
    "zone": BarZone.CAMINHA,
    "address": "R. Direita 125, 4910-155",
    "workingHours": "Ter a Sáb: 12:00h às 15:00h e 19:30h à 01:00h (Fecha Dom e Seg)",
    "workingHoursPT": "Ter a Sáb: 12:00h às 15:00h e 19:30h à 01:00h (Fecha Dom e Seg)",
    "workingHoursEN": "Tue to Sat: 12:00 to 15:00 and 19:30 to 01:00 (Closed Sun and Mon)",
    "styles": [
      "Lager",
      "IPA",
      "Weizen",
      "Stout"
    ],
    "description": "Restaurante que promove a simbiose entre sabores lusitanos, cerveja artesanal e vinhos.",
    "descriptionPT": "Restaurante que promove a simbiose entre sabores lusitanos, cerveja artesanal e vinhos.",
    "descriptionEN": "Restaurant promoting a harmony of Portuguese flavors, craft beer, and wine.",
    "rating": 4.8,
    "reviewsCount": 154,
    "coverPhoto": "https://images.squarespace-cdn.com/content/v1/61e94a43b03e8e6c92a7ab39/411d7f2f-1fb8-42d8-8750-b0bec631f655/01N.png?format=750w",
    "instagramUrl": "https://www.instagram.com/cantodolobo.caminha/",
    "facebookUrl": "https://www.facebook.com/CANTODOLOBO.CAMINHA/?locale=pt_PT",
    "latitude": 41.8784663938095,
    "longitude": -8.838241866030561,
    "hasApplePay": true
  },
  {
    "id": "ribeiros-brewers",
    "name": "Ribeiro’s Brewers (Viana do Castelo)",
    "zone": BarZone.VIANA_DO_CASTELO,
    "address": "R. ds Manjovos n38 ,326, 4900-326",
    "workingHours": "Ter a Qui: 18:00h às 24:00h\nSex e Sáb: 16:00h às 02:00h",
    "workingHoursPT": "Ter a Qui: 18:00h às 24:00h\nSex e Sáb: 16:00h às 02:00h",
    "workingHoursEN": "Tue to Thu: 18:00 to 24:00\nFri and Sat: 16:00 to 02:00",
    "styles": [
      "Pilsner",
      "West Coast IPA",
      "Stout",
      "Amber Ale"
    ],
    "description": "Bar com foco em cerveja artesanal com 50 referências internacionais e tapas.",
    "descriptionPT": "Bar com foco em cerveja artesanal com 50 referências internacionais e tapas.",
    "descriptionEN": "Craft beer bar featuring 50 international labels and tapas.",
    "rating": 4.6,
    "reviewsCount": 88,
    "coverPhoto": "https://images.squarespace-cdn.com/content/v1/61e94a43b03e8e6c92a7ab39/d9232887-876a-4755-a5c0-9ac5c4c14fb4/02N.png?format=750w",
    "instagramUrl": "https://www.instagram.com/ribeirosbrewers/",
    "facebookUrl": "https://www.facebook.com/ribeirosbrewers/?locale=pt_PT",
    "latitude": 41.691434292936336,
    "longitude": -8.82927305432155,
    "hasApplePay": true
  },
  {
    "id": "letraria-viana",
    "name": "Letraria de Viana do Castelo (Viana do Castelo)",
    "zone": BarZone.VIANA_DO_CASTELO,
    "address": "Av. Conde Carreira 28, 4900-343",
    "workingHours": "Geralmente: 17:00h às 00:00h (Verificar no local)",
    "workingHoursPT": "Geralmente: 17:00h às 00:00h (Verificar no local)",
    "workingHoursEN": "Usually: 17:00 to 00:00 (Check on site)",
    "styles": [
      "Letra A",
      "Letra B",
      "Letra C",
      "Letra D",
      "Letra F"
    ],
    "description": "O espaço da Cerveja Letra em Viana do Castelo.",
    "descriptionPT": "O espaço da Cerveja Letra em Viana do Castelo.",
    "descriptionEN": "The Cerveja Letra venue in Viana do Castelo.",
    "rating": 4.7,
    "reviewsCount": 112,
    "coverPhoto": "https://images.squarespace-cdn.com/content/v1/61e94a43b03e8e6c92a7ab39/a8c20890-1379-4e96-8a09-a7a711c8735d/03N.jpg?format=500w",
    "instagramUrl": "https://www.instagram.com/letrariaviana/",
    "facebookUrl": "https://www.facebook.com/letrariaviana/?locale=km_KH",
    "latitude": 41.694551312118016,
    "longitude": -8.831175361394598,
    "hasApplePay": true
  },
  {
    "id": "dona-beer-braga",
    "name": "Dona Beer (Braga)",
    "zone": BarZone.BRAGA,
    "address": "R. 25 de Abril 356 R/c, 4710-914",
    "workingHours": "Seg a Sex: 17:00h às 23:00h (Fecha Sáb e Dom)",
    "workingHoursPT": "Seg a Sex: 17:00h às 23:00h (Fecha Sáb e Dom)",
    "workingHoursEN": "Mon to Fri: 17:00 to 23:00 (Closed Sat and Sun)",
    "styles": [
      "Lager",
      "Weizen",
      "IPA",
      "Stout"
    ],
    "description": "Bar charmoso com vasta seleção de cervejas artesanais locais e internacionais e tapas.",
    "descriptionPT": "Bar charmoso com vasta seleção de cervejas artesanais locais e internacionais e tapas.",
    "descriptionEN": "Charming bar with a wide selection of local and international craft beers and tapas.",
    "rating": 4.7,
    "reviewsCount": 96,
    "coverPhoto": "https://images.squarespace-cdn.com/content/v1/61e94a43b03e8e6c92a7ab39/25b96102-0ed5-479d-aae1-ba10885a5c2b/04N.jpg?format=500w",
    "instagramUrl": "https://www.instagram.com/dona_beer/",
    "facebookUrl": "https://www.facebook.com/DonaBeerCervejaria/?locale=pt_PT",
    "latitude": 41.54811889722582,
    "longitude": -8.419609886621037,
    "hasApplePay": true
  },
  {
    "id": "mal-amado-braga",
    "name": "Mal Amado (Braga)",
    "zone": BarZone.BRAGA,
    "address": "R. Dom Paio Mendes 87, 4700-424",
    "workingHours": "Dom a Qui: 16:00h à 01:00h\nSex e Sáb: 16:00h às 02:00h",
    "workingHoursPT": "Dom a Qui: 16:00h à 01:00h\nSex e Sáb: 16:00h às 02:00h",
    "workingHoursEN": "Sun to Thu: 16:00 to 01:00\nFri and Sat: 16:00 to 02:00",
    "styles": [
      "NEIPA",
      "Sour",
      "Imperial Stout",
      "Saison"
    ],
    "description": "Vibrante adição à cena de bares de Braga perto da Sé.",
    "descriptionPT": "Vibrante adição à cena de bares de Braga perto da Sé.",
    "descriptionEN": "Vibrant addition to Braga's bar scene near the Cathedral.",
    "rating": 4.8,
    "reviewsCount": 154,
    "coverPhoto": "https://images.squarespace-cdn.com/content/v1/61e94a43b03e8e6c92a7ab39/0ad290a4-7206-4671-b5eb-4eee6bbda423/05N.jpg?format=500w",
    "instagramUrl": "https://www.instagram.com/malamado.bar/",
    "facebookUrl": "https://www.facebook.com/malamado.bar/",
    "latitude": 41.54991369750012,
    "longitude": -8.427781389271983,
    "hasApplePay": true
  },
  {
    "id": "craft-draft-braganca",
    "name": "Craft & Draft (Bragança)",
    "zone": BarZone.BRAGANCA,
    "address": "R. Alexandre Herculano 59, 5300-075",
    "workingHours": "Consultar horários no site oficial.",
    "workingHoursPT": "Consultar horários no site oficial.",
    "workingHoursEN": "Check working hours on the official website.",
    "styles": [
      "IPA",
      "Lager",
      "Stout",
      "Belgian Strong"
    ],
    "description": "Considerado o \"Jerusalém das cervejas em Trás-os-Montes\". Grande variedade e seleção cuidada.",
    "descriptionPT": "Considerado o \"Jerusalém das cervejas em Trás-os-Montes\". Grande variedade e seleção cuidada.",
    "descriptionEN": "Considered the craft beer capital of Trás-os-Montes. Great variety and carefully curated selection.",
    "rating": 4.9,
    "reviewsCount": 104,
    "coverPhoto": "https://images.squarespace-cdn.com/content/v1/61e94a43b03e8e6c92a7ab39/981468f3-4e18-4806-a1a3-b99b2aaf69d8/06N.jpg?format=500w",
    "instagramUrl": "https://www.instagram.com/craftdraft.pt/",
    "facebookUrl": "https://www.facebook.com/craftdraftpt/?locale=pt_PT",
    "latitude": 41.80542864976972,
    "longitude": -6.7581469282468385,
    "hasApplePay": true
  },
  {
    "id": "letraria-vila-verde",
    "name": "Letraria de Vila Verde (Vila Verde)",
    "zone": BarZone.VILA_VERDE,
    "address": "Av. Prof. Machado Vilela 147, 4730-684",
    "workingHours": "Recomendado verificar o horário no site oficial.",
    "workingHoursPT": "Recomendado verificar o horário no site oficial.",
    "workingHoursEN": "Recommended to check schedule on the official website.",
    "styles": [
      "Letra A",
      "Letra B",
      "Letra C",
      "Letra D",
      "Letra F"
    ],
    "description": "Tap room da Cerveja Letra na região de Braga.",
    "descriptionPT": "Tap room da Cerveja Letra na região de Braga.",
    "descriptionEN": "Cerveja Letra taproom in the Braga region.",
    "rating": 4.8,
    "reviewsCount": 205,
    "coverPhoto": "https://images.squarespace-cdn.com/content/v1/61e94a43b03e8e6c92a7ab39/855f3d0d-9a95-4de2-af7b-137989339da1/07N.jpg?format=500w",
    "instagramUrl": "https://www.instagram.com/letrariavilaverde/",
    "facebookUrl": "https://www.facebook.com/LetrariaVilaVerde",
    "latitude": 41.650022108237216,
    "longitude": -8.438788151364786,
    "hasApplePay": true
  },
  {
    "id": "hop-trip",
    "name": "Hop Trip - Craft Beer Shop (Matosinhos)",
    "zone": BarZone.MATOSINHOS,
    "address": "R. Heróis de França 617, 4450-159",
    "workingHours": "Ter a Sáb: 15:00h às 21:00h",
    "workingHoursPT": "Ter a Sáb: 15:00h às 21:00h",
    "workingHoursEN": "Tue to Sat: 15:00 to 21:00",
    "styles": [
      "NEIPA",
      "Sour",
      "Session Stout",
      "Saison"
    ],
    "description": "Loja e espaço de degustação em Matosinhos com centenas de referências.",
    "descriptionPT": "Loja e espaço de degustação em Matosinhos com centenas de referências.",
    "descriptionEN": "Shop and tasting room in Matosinhos featuring hundreds of beer references.",
    "rating": 4.8,
    "reviewsCount": 167,
    "coverPhoto": "https://images.squarespace-cdn.com/content/v1/61e94a43b03e8e6c92a7ab39/309741b2-0948-46dd-a062-d5a3a14e8501/08N.png?format=500w",
    "instagramUrl": "https://www.instagram.com/hoptripcraftbeer/",
    "facebookUrl": "https://www.facebook.com/hoptripcraftbeer",
    "latitude": 41.180910406252956,
    "longitude": -8.692768135111493,
    "hasApplePay": true
  },
  {
    "id": "cantinho-cafe",
    "name": "Cantinho café (Castelo Rodrigo)",
    "zone": BarZone.FIGUEIRA_DE_CASTELO_RODRIGO,
    "address": "R. Sinagoga 1, 6440-031",
    "workingHours": "Todos os dias das 12:00-22:30h. Terça-feira: Encerrado",
    "workingHoursPT": "Todos os dias das 12:00-22:30h. Terça-feira: Encerrado",
    "workingHoursEN": "Every day 12:00-22:30. Tuesday: Closed",
    "styles": [
      "Lager",
      "IPA",
      "Stout",
      "Amber Ale"
    ],
    "description": "Local de peregrinação para os fãs da cerveja artesanal. É conhecido pela simpatia dos anfitriões (João e Lena), que proporcionam um ambiente acolhedor e caseiro. A sua localização é em Castelo Rodrigo.",
    "descriptionPT": "Local de peregrinação para os fãs da cerveja artesanal. É conhecido pela simpatia dos anfitriões (João e Lena), que proporcionam um ambiente acolhedor e caseiro. A sua localização é em Castelo Rodrigo.",
    "descriptionEN": "A pilgrimage site for craft beer fans. Known for the warm hospitality of hosts João and Lena in Castelo Rodrigo.",
    "rating": 4.9,
    "reviewsCount": 130,
    "coverPhoto": "https://images.squarespace-cdn.com/content/v1/61e94a43b03e8e6c92a7ab39/17394e60-b9bb-4655-839d-94919cf34deb/09N.jpg?format=500w",
    "instagramUrl": "https://www.instagram.com/cantinhocafe.cr/",
    "facebookUrl": "https://www.facebook.com/cantinhocafe.cr/?locale=pt_PT",
    "latitude": 40.876964198000096,
    "longitude": -6.965209430962654,
    "hasApplePay": true
  },
  {
    "id": "maldita-brewpub",
    "name": "Cerveja Maldita Taproom (Aveiro)",
    "zone": BarZone.AVEIRO,
    "address": "Arco do Comércio 5, 3800-213",
    "workingHours": "Seg a Sáb: 16:00h às 23:00h",
    "workingHoursPT": "Seg a Sáb: 16:00h às 23:00h",
    "workingHoursEN": "Mon to Sat: 16:00 to 23:00",
    "styles": [
      "Maldita Pilsener",
      "Maldita IPA",
      "Maldita Stout",
      "Maldita Barleywine"
    ],
    "description": "Taproom da aclamada Cerveja Maldita em Aveiro.",
    "descriptionPT": "Taproom da aclamada Cerveja Maldita em Aveiro.",
    "descriptionEN": "Taproom of the acclaimed Cerveja Maldita in Aveiro.",
    "rating": 4.7,
    "reviewsCount": 188,
    "coverPhoto": "https://images.squarespace-cdn.com/content/v1/61e94a43b03e8e6c92a7ab39/d568af2d-6127-4357-8374-e8c3a5e35a88/10N.png?format=500w",
    "instagramUrl": "https://www.instagram.com/cerveja_maldita/",
    "facebookUrl": "https://www.facebook.com/CervejaMaldita",
    "latitude": 40.642597446413504,
    "longitude": -8.6519192018918,
    "hasApplePay": true
  },
  {
    "id": "vadia-brewpub",
    "name": "Cerveja Vadia Taproom (Oliveira de Azeméis)",
    "zone": BarZone.OLIVEIRA_DE_AZEMEIS,
    "address": "Travessa Comend. Artur José Gomes Barbosa 576, 3720-005",
    "workingHours": "Seg a Sáb: 15:00h às 23:00h",
    "workingHoursPT": "Seg a Sáb: 15:00h às 23:00h",
    "workingHoursEN": "Mon to Sat: 15:00 to 23:00",
    "styles": [
      "Vadia Lager",
      "Vadia Trigo",
      "Vadia Rubra",
      "Vadia Preta"
    ],
    "description": "Espaço da Cerveja Vadia em Oliveira de Azeméis com vista para a fábrica.",
    "descriptionPT": "Espaço da Cerveja Vadia em Oliveira de Azeméis com vista para a fábrica.",
    "descriptionEN": "Cerveja Vadia spot in Oliveira de Azeméis overlooking the brewery.",
    "rating": 4.8,
    "reviewsCount": 312,
    "coverPhoto": "https://images.squarespace-cdn.com/content/v1/61e94a43b03e8e6c92a7ab39/ca64614b-cfc5-4c6a-a4fc-6eda918dafc5/11N.png?format=500w",
    "instagramUrl": "https://www.instagram.com/vadiabrewpub/",
    "facebookUrl": "https://www.facebook.com/CervejaVadia",
    "latitude": 40.841303680748304,
    "longitude": -8.435096405484218,
    "hasApplePay": true
  },
  {
    "id": "doze-marias",
    "name": "12 Marias (Fermelã)",
    "zone": BarZone.FERMELA,
    "address": "E, N109 74, 3865-127",
    "workingHours": "Todas as Sextas-feiras: 16:00h – 22:00h",
    "workingHoursPT": "Todas as Sextas-feiras: 16:00h – 22:00h",
    "workingHoursEN": "Every Friday: 16:00 – 22:00",
    "styles": [
      "Lager",
      "IPA",
      "Black Beer"
    ],
    "description": "Sala de Provas nas instalações da fábrica, onde é possível degustar as cervejas artesanais da marca acompanhadas de petiscos.",
    "descriptionPT": "Sala de Provas nas instalações da fábrica, onde é possível degustar as cervejas artesanais da marca acompanhadas de petiscos.",
    "descriptionEN": "Tasting room at the brewery facilities, offering craft beer tastings paired with snacks.",
    "rating": 4.8,
    "reviewsCount": 94,
    "coverPhoto": "https://images.squarespace-cdn.com/content/v1/61e94a43b03e8e6c92a7ab39/d7c4447f-b871-424b-a8f9-88010fd88851/12N.jpg?format=500w",
    "instagramUrl": "https://www.instagram.com/12marias_cervejasartesanais/",
    "facebookUrl": "https://www.facebook.com/12mariascervejasartesanais/",
    "latitude": 40.69899584775072,
    "longitude": -8.553025624282064,
    "hasApplePay": true
  },
  {
    "id": "monja-penafiel",
    "name": "Monja (Penafiel)",
    "zone": BarZone.PENAFIEL,
    "address": "Largo Nossa Sra. Ajuda 30, 4560-502",
    "workingHours": "Terça a Quinta: 16:00-0:00h\nSexta e Sábado: 16:00-02:00h\nSegunda-feira: Encerrado",
    "workingHoursPT": "Terça a Quinta: 16:00-0:00h\nSexta e Sábado: 16:00-02:00h\nSegunda-feira: Encerrado",
    "workingHoursEN": "Tuesday to Thursday: 16:00-0:00\nFriday and Saturday: 16:00-02:00\nMonday: Closed",
    "styles": [
      "Blond Ale",
      "Lager",
      "IPA",
      "Belgian"
    ],
    "description": "Um bar moderno no centro histórico, conhecido por servir petiscos simples e cuidados, ideais para acompanhar cerveja.",
    "descriptionPT": "Um bar moderno no centro histórico, conhecido por servir petiscos simples e cuidados, ideais para acompanhar cerveja.",
    "descriptionEN": "A modern bar in the historic center, known for serving simple, carefully crafted snacks paired with beer.",
    "rating": 4.7,
    "reviewsCount": 122,
    "coverPhoto": "https://images.squarespace-cdn.com/content/v1/61e94a43b03e8e6c92a7ab39/9fd3c7d8-c098-4ebe-9947-389f7fc7ba22/13N.png?format=500w",
    "instagramUrl": "https://www.instagram.com/monjapenafiel/",
    "facebookUrl": "https://www.facebook.com/monjadepenafiel",
    "latitude": 41.2063331017255,
    "longitude": -8.282558856730631,
    "hasApplePay": true
  },
  {
    "id": "lovecraft-feira",
    "name": "Lovecraft Public House Feira (Santa Maria da Feira)",
    "zone": BarZone.SANTA_MARIA_DA_FEIRA,
    "address": "Rua das Fogaceiras 21, 4520-200",
    "workingHours": "Segunda a Sábado 15:00h às 01:00h",
    "workingHoursPT": "Segunda a Sábado 15:00h às 01:00h",
    "workingHoursEN": "Monday to Saturday 15:00 to 01:00",
    "styles": [
      "Imperial Stout",
      "NEIPA",
      "Sour",
      "Gluten Free"
    ],
    "description": "Bar de cerveja artesanal em Santa Maria da Feira com ambiente acolhedor, petiscos e opções vegetarianas/vegan.",
    "descriptionPT": "Bar de cerveja artesanal em Santa Maria da Feira com ambiente acolhedor, petiscos e opções vegetarianas/vegan.",
    "descriptionEN": "Craft beer bar in Santa Maria da Feira with a cozy atmosphere, snacks, and vegetarian/vegan options.",
    "rating": 4.8,
    "reviewsCount": 167,
    "coverPhoto": "https://images.squarespace-cdn.com/content/v1/61e94a43b03e8e6c92a7ab39/0aa11711-9295-4c51-a12b-ab7978e89363/15N.jpg?format=500w",
    "instagramUrl": "https://www.instagram.com/lovecraftfeira/",
    "facebookUrl": "https://www.facebook.com/lovecraftbeers/?locale=pt_PT",
    "latitude": 40.92575249331072,
    "longitude": -8.541609317432991,
    "hasApplePay": true
  },
  {
    "id": "cobo-taproom",
    "name": "Cobo Taproom (Guimarães)",
    "zone": BarZone.GUIMARAES,
    "address": "Praça de São Tiago 11, 4800-445",
    "workingHours": "Quarta a Domingo: 18:00h às 01:00h",
    "workingHoursPT": "Quarta a Domingo: 18:00h às 01:00h",
    "workingHoursEN": "Wednesday to Sunday: 18:00 to 01:00",
    "styles": [
      "Lager",
      "NEIPA",
      "Sour",
      "Quadrupel"
    ],
    "description": "Taproom em Guimarães dedicado às melhores criações artesanais.",
    "descriptionPT": "Taproom em Guimarães dedicado às melhores criações artesanais.",
    "descriptionEN": "Taproom in Guimarães dedicated to the finest craft creations.",
    "rating": 4.9,
    "reviewsCount": 154,
    "coverPhoto": "https://images.squarespace-cdn.com/content/v1/61e94a43b03e8e6c92a7ab39/086e437c-9d97-4387-af13-37ece0c29ba8/17N.jpg?format=500w",
    "instagramUrl": "https://www.instagram.com/prost_guimaraes/",
    "facebookUrl": "https://www.facebook.com/p/PROST-100086242280709/?locale=pt_BR",
    "latitude": 41.44362147784739,
    "longitude": -8.293120436800848,
    "hasApplePay": true
  }
];
