/**
 * Google Maps URL Mapping for all bars.
 * Derived from the attached CSV specification.
 */

export const BAR_MAPS_URLS: Record<string, string> = {
  'azores-brewing': 'https://maps.app.goo.gl/kbn5sSaiX7LUPHBD7',
  'beerstore-pt': 'https://maps.app.goo.gl/SFNy6i7EwRgk21ru6',
  'vulcana': 'https://maps.app.goo.gl/7SXGUAKYJJvnoeXc9',
  'koriska': 'https://maps.app.goo.gl/53n15WwkpqjU8ezp6',
  'epicura-coimbra': 'https://maps.app.goo.gl/99PBDEAaeUveoeRDA',
  'praxis-coimbra': 'https://maps.app.goo.gl/6h2VsQ9qJUUkh8yC7',
  'tough-love-aveiro': 'https://maps.app.goo.gl/EQekhLX6eXBkwmwC7',
  'letraria-obidos': 'https://maps.app.goo.gl/ernNYUK2eyf3FiSv5',
  'five-e-meio-ericeira': 'https://maps.app.goo.gl/vSj2VM9dzgvTTYb4A',
  'emporio-ericeira': 'https://maps.app.goo.gl/5h2Kpkoc6dnLq4aT9',
  'mean-sardine-ericeira': 'https://maps.app.goo.gl/BCC2SYxgUuMSJ6JB6',
  'parreirinha-ericeira': 'https://maps.app.goo.gl/GNM2NKHqEeAEBseK6',
  'hopsin-colares': 'https://maps.app.goo.gl/66paxn5UmryPrxyc9',
  'villa-craft-sintra': 'https://maps.app.goo.gl/8xcwFjiVjvCKQJSM7',
  'beer-cascais': 'https://maps.app.goo.gl/Y7oKxMWjCTa5CA8cA',
  'namedida-cascais': 'https://maps.app.goo.gl/jLV6vVA6UXNdtPrx9',
  'crafty-cellar-cascais': 'https://maps.app.goo.gl/WvKU76RAFaqz4xM1A',
  'crows-bar-cascais': 'https://maps.app.goo.gl/Me2jDFPTi4xvKciK8',
  'dois-corvos-marvila': 'https://maps.app.goo.gl/9xhazaPbKxCzZTvx9',
  'dois-corvos-intendente': 'https://maps.app.goo.gl/qAAhJpbtEgxhXLSw8',
  'musa-marvila': 'https://maps.app.goo.gl/ewjSe89V25Npogrq5',
  'musa-bica': 'https://maps.app.goo.gl/KbbYtHuGiTS4Hi1W8',
  'fermentage-marvila': 'https://maps.app.goo.gl/3m6XHtiq6x1mjpw17',
  'pravda-marvila': 'https://maps.app.goo.gl/yuPTBrWS3kXsSpPP8',
  'lx-brewery': 'https://maps.app.goo.gl/47sTR2kERzdFNnxQ6',
  'oficina-da-cerveja': 'https://maps.app.goo.gl/PzD9vf8NAERPY3Hx8',
  'oitava-colina-graca': 'https://maps.app.goo.gl/cXsai7F73FnZBwmP9',
  'duque-brewpub': 'https://maps.app.goo.gl/Q81HhHpcfR5HmVTU7',
  'canil-baixa': 'https://maps.app.goo.gl/889rHDZUVuMGPS7q7',
  'canil-marques': 'https://maps.app.goo.gl/X4SD59NBKVC56LxVA',
  'cerveteca': 'https://maps.app.goo.gl/2KzaGTzDACiS1uxC6',
  'artesanalis': 'https://maps.app.goo.gl/CeptmAox76bP6iXr6',
  'flor-de-lupulo': 'https://maps.app.goo.gl/t2MWA2LtLTo7K2nA6',
  'sputnik-lisboa': 'https://maps.app.goo.gl/sx3idSmDJjesPn8v7',
  'beer-station-lisboa': 'https://maps.app.goo.gl/fYuiLS2t5aLpGypN9',
  'sailors-bar': 'https://maps.app.goo.gl/PTpX3SpuLMP9yLrK9',
  'gulden-draak-vasco': 'https://maps.app.goo.gl/EGy1KCcvBSNjDZHn9',
  'lovecraft-lisboa': 'https://maps.app.goo.gl/43e7n56mF7g62dJLA',
  'browers-beato': 'https://maps.app.goo.gl/XAKWeTwEFcTGyXB16',
  'queen-ale-lisboa': 'https://maps.app.goo.gl/SCGQfTjZeyoNa3xz7',
  'funchal-taproom': 'https://maps.app.goo.gl/jqCVM2TsXb7FSLWXA',
  'fuga-cidade-2014': 'https://maps.app.goo.gl/7NfTxv7ETYprceCTA',
  'beer-house-funchal': 'https://maps.app.goo.gl/zLFM4PNcC2KG31cx9',
  'canto-do-lobo': 'https://maps.app.goo.gl/BBcxmGW3R32tBX2BA',
  'ribeiros-brewers': 'https://maps.app.goo.gl/2v7eNm6DCVtKthnn7',
  'letraria-viana': 'https://maps.app.goo.gl/mtJd4wSYyBx18TdcA',
  'dona-beer-braga': 'https://maps.app.goo.gl/qPLFTet9vZ8YXk2D6',
  'mal-amado-braga': 'https://maps.app.goo.gl/CpdG8qDaghTRWBKS7',
  'craft-draft-braganca': 'https://maps.app.goo.gl/ZFgZqK5zyCFNWAJ48',
  'letraria-vila-verde': 'https://maps.app.goo.gl/nktuPd7rwEGMzPwD6',
  'hop-trip': 'https://maps.app.goo.gl/G1o5MD2WWuhWxFwM9',
  'tough-love-cask': 'https://maps.app.goo.gl/rY4uMAhEK1tad7s1A',
  'gulden-draak-porto': 'https://maps.app.goo.gl/b5Vbg4wLqemmzBXg6',
  'baobab-porto': 'https://maps.app.goo.gl/APyXz9CRiBosXx6KA',
  'cervejaria-carmo': 'https://maps.app.goo.gl/nXjxhuzhMjTjh4qm8',
  'musa-virtudes': 'https://maps.app.goo.gl/CvY7esWPGmwfCCwF6',
  'catraio': 'https://maps.app.goo.gl/DTsnTne4NikqvVUj7',
  'nortada': 'https://maps.app.goo.gl/G5TyszDFBydt13aw9',
  'armazem-da-cerveja': 'https://maps.app.goo.gl/YhbXMCFV62L1YN8q9',
  'fabrica-da-picaria': 'https://maps.app.goo.gl/NRTHVxkFw8vBoT9j9',
  'levare-brewpub': 'https://maps.app.goo.gl/AjwwxWGiSTPh9ygBA',
  'magnifica-evora': 'https://maps.app.goo.gl/MttvNPLomBR8EPQ79',
  'barona': 'https://maps.app.goo.gl/6LAXwfMZux1YqCVj8',
  'skal-pub': 'https://maps.app.goo.gl/UZbnZXzZCkz4JgvB9',
  'capt-tap': 'https://maps.app.goo.gl/NLKCBhzBVemUDxkC8',
  'ophiussa-taproom': 'https://maps.app.goo.gl/6LLVurtCk3pqDcrw7',
  'lagos-beer-co': 'https://maps.app.goo.gl/6eJVTdEL6R49Gfaj6',
  'collab-bar-lagos': 'https://maps.app.goo.gl/g3kZbyKtXjdtr7X6A',
  'mania-beer-brewery': 'https://maps.app.goo.gl/Pxbw9ZQ5n98tUJvo7',
  'algarvian-brewing': 'https://maps.app.goo.gl/34pHfp8XzssfYDkG7',
  'boheme-faro': 'https://maps.app.goo.gl/rvrBWfoio54923K26',
  'boheme-tavira': 'https://maps.app.goo.gl/yPvD8q7WqSaTkHBW8',
  'nanobrew-fuzeta': 'https://maps.app.goo.gl/nLia41JE9WKTMDhh9',
  'craft-heritage': 'https://maps.app.goo.gl/VQ4iyZDk9g8ghzgh6',
  'vilhoa': 'https://maps.app.goo.gl/8jZdwze6au5c5Vn29',
  'guldendraak-casa-lisboa': 'https://maps.app.goo.gl/TYp6DCRog3JK1o6x6',
  'dos-santos-lagoa': 'https://maps.app.goo.gl/nqDAmoZzbw7u2Bo3A',
  'cerveja-dos-diabos': 'https://maps.app.goo.gl/WSXNJfi54CQbBHKcA',
  'cantinho-cafe': 'https://maps.app.goo.gl/A72BmiCPkXf663UV6',
  'cerveja-acor': 'https://maps.app.goo.gl/iSUdFF2sgRZUMUsT6',
  'cerveja-boazona': 'https://maps.app.goo.gl/8xbxtwH8Ws4xhn9Q7',
  'maldita-brewpub': 'https://maps.app.goo.gl/YM1D4Tc96iNxJp3r9',
  'taverna-lusitana': 'https://maps.app.goo.gl/C3TkNZK26eJSG61AA',
  'vadia-brewpub': 'https://maps.app.goo.gl/xcHa6KoVDUhgy7dh7',
  'letraria-downtown': 'https://maps.app.goo.gl/1MFYJVQ3jXtbhBhi6',
  'deuses-do-malte': 'https://maps.app.goo.gl/RFCe1duCjG2o4hJf7',
  'doze-marias': 'https://maps.app.goo.gl/U3XzQ1NA8hynfPt66',
  'monja-penafiel': 'https://maps.app.goo.gl/LAqBusJkm7nudGw49',
  'letraria-braga-garden': 'https://maps.app.goo.gl/boBtkZnnaRdjdrPq9',
  'lovecraft-feira': 'https://maps.app.goo.gl/KE1c8C61mcaghXQE6',
  'quimera-brewpub': 'https://maps.app.goo.gl/CjD56JQCraE8BTkM6',
  'amo-brewery': 'https://maps.app.goo.gl/2qBe663hBRjZQPXu8',
  'lispoa-craft-beer': 'https://maps.app.goo.gl/pyrFF7BFKXrvsHcT8',
  'outro-lado-lisboa': 'https://maps.app.goo.gl/j2ZDRnB6m2YDMGLo6',
  'brew-portugal': 'https://maps.app.goo.gl/kHqxPX1oqaUBmTsf7',
  'crafty-corner-alfama': 'https://maps.app.goo.gl/iVT9pV8d87XnnKiB6',
  'pils-lisboa': 'https://maps.app.goo.gl/urWzeyPiXCYXkafg7',
  'musa-da-praia': 'https://maps.app.goo.gl/w1xovbH8P68QXkn97',
  'letraria-ponte-lima': 'https://maps.app.goo.gl/AZshPUnJtEgPVApG8',
  'prost-guimaraes': 'https://maps.app.goo.gl/GLT69RTWbTKR4aGPA',
  'beberico-sra-hora': 'https://maps.app.goo.gl/A7mxqoNoNpmNtK35A',
  'jagora-gaia': 'https://maps.app.goo.gl/XL6tUj7gCv7bCjKt8',
  'surviaria-amarante': 'https://maps.app.goo.gl/9EUaJnNtouykagK57',
  'andsome-beer': 'https://maps.app.goo.gl/osD4meA5MvQ5eMJv9',
  'hale-mary-lobos': 'https://maps.app.goo.gl/3n7W852sj79UGDCN6',
  'bela-cerveja-arrifes': 'https://maps.app.goo.gl/R65U7KJ969t1b5628',
  'marrafa-jesufrei': 'https://maps.app.goo.gl/d3CBCgpZcZMAQtJKA',
  'bah-craft-beer': 'https://maps.app.goo.gl/DRJqN2J5jYYnvA6p6',
  'malaica-caldas': 'https://maps.app.goo.gl/ZRwyz12oFy8qZT7y6',
  'o-bandido': 'https://maps.app.goo.gl/yKXUuiYypAX4ggCA7'
};

export function getBarGoogleMapsUrl(barId: string, fallbackAddress: string): string {
  if (BAR_MAPS_URLS[barId]) {
    return BAR_MAPS_URLS[barId];
  }
  // fallback search query if id not mapped somehow
  return `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(fallbackAddress)}`;
}
